{
  lib,
  pkgs,
  config,
  ...
}:
with lib; let
  cfg = config.blackmatter.components.nvim.plugin.groups.lsp;
  common = import ../../common;
  configPath = "${common.includesPath}/lsp";

  # Platform detection for LSP tooling
  isDarwin = pkgs.stdenv.isDarwin;
  isLinux = pkgs.stdenv.isLinux;

  # C/C++ compiler for LSP servers (clangd, ccls)
  cCompiler = if isDarwin then pkgs.clang else pkgs.gcc;

  # Wrap ruby-lsp to export GEM_PATH as an environment variable.
  # The Nix gem wrapper sets Gem.paths at the Ruby level, but ruby-lsp's
  # composed bundle resolution uses bundler which needs GEM_PATH in the env.
  rubyLspWrapped = let
    rubyLsp = pkgs.rubyPackages_3_4.ruby-lsp;
    allGems = [rubyLsp] ++ (rubyLsp.propagatedBuildInputs or []) ++ [pkgs.ruby_3_4];
    gemPath = lib.concatMapStringsSep ":" (d: "${d}/lib/ruby/gems/3.4.0") allGems;
  in
    pkgs.writeShellScriptBin "ruby-lsp" ''
      export GEM_PATH="${gemPath}''${GEM_PATH:+:$GEM_PATH}"
      exec ${rubyLsp}/bin/ruby-lsp "$@"
    '';
in {
  options.blackmatter.components.nvim.plugin.groups.lsp = {
    enable = mkEnableOption "LSP support";

    # Feature toggles
    features = {
      inlayHints = {
        enable = mkEnableOption "inlay hints" // {default = true;};
      };

      diagnostics = {
        enable = mkEnableOption "diagnostics" // {default = true;};
      };

      codeActions = {
        enable = mkEnableOption "code actions" // {default = true;};
      };

      formatting = {
        enable = mkEnableOption "LSP formatting" // {default = false;};
        description = "Enable LSP-based formatting (may conflict with conform.nvim)";
      };
    };

    # Required plugins (auto-enabled when group is enabled)
    requiredPlugins = mkOption {
      type = types.listOf types.str;
      default = [
        "neovim.nvim-lspconfig"
        "williamboman.mason.nvim"
        "williamboman.mason-lspconfig.nvim"
        "hrsh7th.nvim-cmp"
        "hrsh7th.cmp-nvim-lsp"
      ];
      readOnly = true;
      description = "Plugins required for LSP functionality";
    };

    # Optional enhancement plugins
    optionalPlugins = {
      helm = mkEnableOption "vim-helm for Kubernetes manifests" // {default = true;};
    };
  };

  # No imports needed - plugins loaded via registry

  config = mkMerge [
    (mkIf cfg.enable {
      # Install development tooling and language servers
      home.packages = with pkgs;
      with dotnetCorePackages;
      with rubyPackages_3_4;
      with luajitPackages;
      with php84Packages;
      with nodePackages; [
        go
        cCompiler # Platform-specific: clang on macOS, gcc on Linux
        zulu
        nixd
        bash
        opam
        unzip
        cmake
        ninja
        nodejs
        nodePackages.typescript-language-server
        gopls
        clang-tools
        codeium
        rubyLspWrapped
        tree-sitter
        luarocks-nix
        # swift-format # Disabled: swift build failures
        rust-analyzer
        bash-language-server
        shellcheck
        nushell
        powershell
        # powershell-editor-services # Not available in nixpkgs 24.11
        basedpyright
        ruff
        # sourcekit-lsp # Disabled: swift build failures
        markdown-oxide
        zls
        texlivePackages.latexindent
        (python312.withPackages (ps: with ps; [pip]))
      ];

      # Install core Lua configuration files
      home.file."${configPath}/init.lua".source = ./init.lua;
      home.file."${configPath}/filetypes.lua".source = ./filetypes.lua;
      home.file."${configPath}/lspsaga.lua".source = ./lspsaga.lua;
      home.file."${configPath}/diagnostics.lua".source = ./diagnostics.lua;
      home.file."${configPath}/keybindings.lua".source = ./keybindings.lua;
      home.file."${configPath}/illuminate.lua".source = ./illuminate.lua;
      # Single source of truth for Nix-managed servers and their configs
      home.file."${configPath}/nix_managed_servers.lua".source = ./nix_managed_servers.lua;

      # Generate feature flags for Lua
      home.file."${configPath}/features.lua".text = ''
        -- Auto-generated by Nix LSP group configuration
        -- DO NOT EDIT MANUALLY
        return {
          inlay_hints = ${boolToString cfg.features.inlayHints.enable},
          diagnostics = ${boolToString cfg.features.diagnostics.enable},
          code_actions = ${boolToString cfg.features.codeActions.enable},
          formatting = ${boolToString cfg.features.formatting.enable},
        }
      '';

      # Enable required plugins
      blackmatter.components.nvim.plugins = {
        neovim.nvim-lspconfig.enable = true;
        williamboman."mason.nvim".enable = true;
        williamboman."mason-lspconfig.nvim".enable = true;
        hrsh7th.nvim-cmp.enable = true;
        hrsh7th.cmp-nvim-lsp.enable = true;
        glepnir."lspsaga.nvim".enable = true;
        ray-x."lsp_signature.nvim".enable = true;
        folke."trouble.nvim".enable = true;
        rachartier."tiny-inline-diagnostic.nvim".enable = true;
        RRethy.vim-illuminate.enable = true;
        # neotest — test runner framework + adapters
        nvim-neotest.neotest.enable = true;
        nvim-neotest.nvim-nio.enable = true;
        nvim-neotest.neotest-go.enable = true;
        nvim-neotest.neotest-jest.enable = true;
        nvim-neotest.neotest-plenary.enable = true;
        nvim-neotest.neotest-python.enable = true;
        rouge8.neotest-rust.enable = true;
      };
    })

    # Optional plugins
    (mkIf (cfg.enable && cfg.optionalPlugins.helm) {
      blackmatter.components.nvim.plugins.towolf.vim-helm.enable = true;
    })
  ];
}
