# Fish completion for blnvim (blackmatter neovim)

complete -c blnvim -s u -r -F -d 'Use this config file'
complete -c blnvim -l cmd -r -d 'Execute command before config'
complete -c blnvim -s c -r -d 'Execute command after config'
complete -c blnvim -s d -d 'Diff mode'
complete -c blnvim -s e -d 'Ex mode'
complete -c blnvim -s h -d 'Show help'
complete -c blnvim -l headless -d 'Run without UI'
complete -c blnvim -s l -r -F -d 'Execute Lua script'
complete -c blnvim -s n -d 'No swap file'
complete -c blnvim -s o -r -d 'Open N windows horizontally'
complete -c blnvim -s O -r -d 'Open N windows vertically'
complete -c blnvim -s p -r -d 'Open N tab pages'
complete -c blnvim -s r -r -F -d 'Recover from swap file'
complete -c blnvim -s R -d 'Read-only mode'
complete -c blnvim -s S -r -F -d 'Source file after loading'
complete -c blnvim -l startuptime -r -F -d 'Write startup timing to file'
complete -c blnvim -s V -r -d 'Verbose level'
complete -c blnvim -l version -d 'Show version'
complete -c blnvim -l clean -d 'Skip config and plugins'
complete -c blnvim -l noplugin -d 'Skip loading plugins'
